//**************************************************************************
// Nombre......: JVentanaLSRA.java
// Proyecto....: Open SimMPLS
// Descripción.: Implementación de una ventana que obtendrá los parámetros
// ............: necesarios para la configuración de un nodo LSRA.
// Fecha.......: 19/02/2004
// Autor/es....: Manuel Domínguez Dorado
// ............: ingeniero@ManoloDominguez.com
// ............: http://www.ManoloDominguez.com
//**************************************************************************

package simMPLS.interfaz.dialogos;

import simMPLS.interfaz.utiles.*;
import simMPLS.interfaz.dialogos.*;
import simMPLS.entradasalida.red.*;
import java.awt.*;
import javax.swing.*;

/**
 * Esta clase implementa una ventana gracias a la cual el usuario de la aplicación
 * peude ponerse en contacto con los creadores de la misma.
 * @author <B>Manuel Domínguez Dorado</B><br><A
 * href="mailto:ingeniero@ManoloDominguez.com">ingeniero@ManoloDominguez.com</A><br><A href="http://www.ManoloDominguez.com" target="_blank">http://www.ManoloDominguez.com</A>
 * @version 1.0
 */
public class JVentanaComentario extends javax.swing.JDialog {

    /**
     * Ese método crea una nueva instancia de JVentanaEmisor
     * @param di Dispensador de imágenes global de la aplicación.
     * @param parent Ventana padre dentro de la cual se mostrará esta ventana de tipo
     * JVentanaComentario.
     * @param modal TRUE indica que la ventana impedirá que se pueda seleccionar cualquier otra
     * parte de la interfaz hasta que se cierre. FALSE indica que esto no es asi.
     * @since 1.0
     */
    public JVentanaComentario(TDispensadorDeImagenes di, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        ventanaPadre = parent;
        dispensadorDeImagenes = di;
        enviadorDeCorreo = new TSMTP();
        initComponents();
        initComponents2();
    }

    /**
     * Este método termina de iniciar algunos valroes de atributos que no queden
     * correctamente preparados en el constructor.
     * @since 1.0
     */    
    public void initComponents2() {
        java.awt.Dimension tamFrame=this.getSize();
        java.awt.Dimension tamPadre=ventanaPadre.getSize();
        setLocation((tamPadre.width-tamFrame.width)/2, (tamPadre.height-tamFrame.height)/2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        panelPrincipal = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        comentario = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        servidor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        remitente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setTitle(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("JVentanaComentario.ContactarAutores"));
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Dialog", 0, 12));
        jButton2.setIcon(dispensadorDeImagenes.obtenerIcono(TDispensadorDeImagenes.SOBRE_EMAIL));
        jButton2.setMnemonic(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("JVentanaComentario.mnemonico.enviar").charAt(0));
        jButton2.setText(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("JVentanaComentario.Send"));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicEnAceptar(evt);
            }
        });

        panelBotones.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 110, -1));

        jButton3.setFont(new java.awt.Font("Dialog", 0, 12));
        jButton3.setIcon(dispensadorDeImagenes.obtenerIcono(TDispensadorDeImagenes.CANCELAR));
        jButton3.setMnemonic(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("JVentanaComentario.mnemonico.cancelar").charAt(0));
        jButton3.setText(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("JVentanaComentario.Cancel"));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicEnCancelar(evt);
            }
        });

        panelBotones.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 15, 110, -1));

        panelPrincipal.add(panelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 255, 400, 55));

        jLabel1.setIcon(dispensadorDeImagenes.obtenerIcono(TDispensadorDeImagenes.COMENTARIO));
        jLabel1.setText(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("JVentanaComentario.tooltip.send"));
        panelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, -1));

        comentario.setLineWrap(true);
        jScrollPane1.setViewportView(comentario);

        panelPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 165, 370, 90));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("JVentanaComentario.tooltip.SMTPServer"));
        panelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 75, 170, -1));

        panelPrincipal.add(servidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 75, 190, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("JVentanaComentario.email"));
        panelPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 105, 145, -1));

        panelPrincipal.add(remitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 105, 210, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel4.setText(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("JVentanaComentario.Comentario"));
        panelPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 145, 365, -1));

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 310));

        pack();
    }//GEN-END:initComponents

private void clicEnCancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicEnCancelar
    this.setVisible(false);
    this.dispose();
}//GEN-LAST:event_clicEnCancelar

private void clicEnAceptar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicEnAceptar
    int estado = comprobarDatos();
    if (estado == CORRECTO) {
        int estadoConexion = enviadorDeCorreo.iniciarSMTP(this.servidor.getText(), this.remitente.getText());
        if (estadoConexion != TSMTP.ERROR_CONECTANDO) {
            int estadoEnvio = enviadorDeCorreo.enviarNotificacion(this.comentario.getText());
            if (estadoEnvio != 0) {
                JVentanaAdvertencia va = new JVentanaAdvertencia(ventanaPadre, true, dispensadorDeImagenes);
                va.mostrarMensaje(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("VentanaComentario.ErrorEnviando"));
                va.show();
            } else {
                this.setVisible(false);
                this.dispose();
            }
        } else {
            JVentanaAdvertencia va = new JVentanaAdvertencia(ventanaPadre, true, dispensadorDeImagenes);
            va.mostrarMensaje(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("JVentanaComentario.ErrorAlConectar"));
            va.show();
        }
    } else {
        JVentanaAdvertencia va = new JVentanaAdvertencia(ventanaPadre, true, dispensadorDeImagenes);
        switch (estado) {
            case SERVIDOR_VACIO:{
                va.mostrarMensaje(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("JVentanaComentario.debePonerSMTP"));
                break;
            }
            case REMITE_VACIO:{
                va.mostrarMensaje(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("JVentanaComentario.DebePonerSuEmail"));
                break;
            }
            case SIN_COMENTARIO: {
                va.mostrarMensaje(java.util.ResourceBundle.getBundle("simMPLS/lenguajes/lenguajes").getString("JVentanaComentario.DebePonerComentario"));
                break;
            }
        }
        va.show();
    }
}//GEN-LAST:event_clicEnAceptar

/**
 * Este método comprueba que los datos introducidos son correctos para enviar el
 * comentario a los autores del programa.
 * @return Un código de error. Alguna de las cosntantesdefinidas en la clase.
 * @since 1.0
 */
    public int comprobarDatos() {  
        if (servidor.getText().equals(""))
            return this.SERVIDOR_VACIO;
        if (remitente.getText().equals(""))
            return this.REMITE_VACIO;
        if (comentario.getText().equals(""))
            return this.SIN_COMENTARIO;
        return this.CORRECTO;
    }

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * Constante que indica que el mensaje se ha enviado correctamente.
     * @since 1.0
     */    
    public static final int CORRECTO = 0;
    /**
     * Esta constanteindica que el campo donde se debía especificar el servidor SMTP,
     * se ha dejado vacío.
     * @since 1.0
     */    
    public static final int SERVIDOR_VACIO = 1;
    /**
     * Esta constante indica que el lugar donde se debía escribir el comentario a
     * enviar, se ha dejado vacio.
     * @since 1.0
     */    
    public static final int SIN_COMENTARIO = 2;
    /**
     * Esta constante indica que el campo donde se debía especificar el remitente del
     * mensaje, se ha dejado vacío.
     * @since 1.0
     */    
    public static final int REMITE_VACIO = 3;

    private TDispensadorDeImagenes dispensadorDeImagenes;
    private Frame ventanaPadre;
    private TSMTP enviadorDeCorreo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea comentario;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField remitente;
    private javax.swing.JTextField servidor;
    // End of variables declaration//GEN-END:variables

}
